_BASE_: base-holodino.yaml
MODEL:
  RESNETS:
    DEPTH: 34
    KERNEL_SIZE: 9
    OUT_FEATURES: ["res3", "res4"]
  MaskDINO:
    DEC_LAYERS: 5
  SEM_SEG_HEAD:
    TRANSFORMER_ENC_LAYERS: 4
    IN_FEATURES:
    - res3
    - res4
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES:
    - res3
    - res4
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 5000
INPUT:
  IMAGE_SIZE: 256
TEST:
  EVAL_PERIOD: 1000